on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag raspberry-pi-pico-docker-dev:$(date +%s)

    - name: Run Docker container 
      run: docker run -d -it -u $(id -u):$(id -g) --name pico-sdk --mount type=bind,source=${PWD},target=/home/dev/src raspberry-pi-pico-docker-dev:latest 
      
    - name: CMake configure
      run: docker exec -it pico-sdk "cmake -S /home/dev/src/build -B /home/dev/src/build -G Ninja"

    - name: Build
      # Build your program with the given configuration
      run: docker exec -it pico-sdk "cmake --build /home/dev/src/build"

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: docker exec -it pico-sdk "cd /home/dev/src/build && ninja test"
    
